stages:
  - lint
  - build
  - check

variables:
  PUBLIC_API_URL: "http://127.0.0.1:8000"

lint backend:
  stage: lint
  image: python:3.11
  script:
    - echo "Linting the backend"
    - python --version
    - pip install --upgrade pip
    - pip install black
    - cd backend
    - black --check .
  only:
    - merge_requests
    
lint frontend:
  stage: lint
  image: node:19
  script:
    - echo "Linting the frontend"
    - cd frontend
    - npm ci
    - npm run lint
  only:
    - merge_requests

check frontend:
  stage: check
  image: node:19
  script:
    - echo "Checking the frontend"
    - cd frontend
    - npm ci
    - npm run check

build:
  stage: build
  image: node:19
  script:
    - echo "Building the project"
    - cd frontend
    - npm ci
    - npm run build
  only:
    - merge_requests




