"""Init v2

Revision ID: 6e9f7dfcb356
Revises: 
Create Date: 2023-08-10 23:12:44.181840

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e9f7dfcb356"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("semester", sa.String(), nullable=False),
        sa.Column("responsible", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", "semester"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("email"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "course_question",
        sa.Column("question_id", sa.String(), nullable=False),
        sa.Column("course_id", sa.String(), nullable=False),
        sa.Column("course_semester", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id", "course_semester"],
            ["courses.id", "courses.semester"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("question_id", "course_id", "course_semester"),
    )
    op.create_table(
        "enrollment",
        sa.Column("user_email", sa.String(), nullable=False),
        sa.Column("course_id", sa.String(), nullable=False),
        sa.Column("course_semester", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "lecturer", "teaching assistant", "student", name="enrollment_roles"
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["course_id", "course_semester"],
            ["courses.id", "courses.semester"],
        ),
        sa.ForeignKeyConstraint(
            ["user_email"],
            ["users.email"],
        ),
        sa.PrimaryKeyConstraint("user_email", "course_id", "course_semester"),
    )
    op.create_table(
        "invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("course_id", sa.String(), nullable=True),
        sa.Column("course_semester", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id", "course_semester"],
            ["courses.id", "courses.semester"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("date_available", sa.Date(), nullable=True),
        sa.Column("course_id", sa.String(), nullable=True),
        sa.Column("course_semester", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id", "course_semester"],
            ["courses.id", "courses.semester"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reflections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("timestamp", sa.Date(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("is_interesting", sa.Boolean(), nullable=True),
        sa.Column("is_problematic", sa.Boolean(), nullable=True),
        sa.Column("is_sorted", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("unit_id", sa.Integer(), nullable=True),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_content", sa.JSON(), nullable=True),
        sa.Column("unit_id", sa.Integer(), nullable=True),
        sa.Column("course_id", sa.String(), nullable=True),
        sa.Column("course_semester", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id", "course_semester"],
            ["courses.id", "courses.semester"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reports")
    op.drop_table("reflections")
    op.drop_table("units")
    op.drop_table("invitations")
    op.drop_table("enrollment")
    op.drop_table("course_question")
    op.drop_table("users")
    op.drop_table("questions")
    op.drop_table("courses")
    # ### end Alembic commands ###
